### ISSUE TITLE
Call to undefined function Moontoast\Math\bcadd()

### ISSUE THREAD

**Issue by r3h6** [ramsey/moontoast-math#10]
Error: Call to undefined function Moontoast\Math\bcadd()

/var/www/vendor/moontoast/math/src/Moontoast/Math/BigNumber.php:699
/var/www/vendor/ramsey/uuid/src/Converter/Number/BigNumberConverter.php:34
/var/www/vendor/ramsey/uuid/src/Uuid.php:364

**Comment by shrikeh** [comment]
Do you have the _bcmath_ library installed, as that is normally the issue on errors such as this?
