### ISSUE TITLE
Is there value in a standardised interface?

### ISSUE THREAD

**Issue by shrikeh** [ramsey/moontoast-math#11]
I have been using the excellent [bignumbers](https://github.com/Litipk/php-bignumbers) library by @Litipk recently, and just came across this one as part of using @ramsey's UUID library.

As these are both implementations to solve the inherent issues with PHP with large numbers and precision, is there any value in there being a unified interface so that end users can easily use either without refactoring?

Just a thought as I'm a great fan of the interoperability initiatives in Containers, Requests, etc.

**Comment by ramsey** [comment]
@shrikeh, I agree that there's value in having a standard interface, and I'd love to work with @Litipk to help create that. Maybe we can pitch it to the @php-fig.

As a side note, I'm interested in deprecating moontoast/math and using a different math library for ramsey/uuid. I'll take a look at litipk/php-bignumbers as a potential solution. Thanks for the pointer.
