### ISSUE TITLE
composer.json information is not correct

### ISSUE THREAD

**Issue by xcorp1986** [ramsey/moontoast-math#18]
it's still point to [https://github.com/moontoast/math](https://github.com/moontoast/math)，while your code is newer

**Comment by ramsey** [comment]
Thanks for reporting this. Can you point out the line in the `composer.json` file that is incorrect? I’m having trouble finding it. Thanks!

**Comment by xcorp1986** [comment]
> Thanks for reporting this. Can you point out the line in the `composer.json` file that is incorrect? I’m having trouble finding it. Thanks!

it's in line 2 in composer.json
"name": "moontoast/math",
BTW,u can referer to https://packagist.org in section “Publishing Packages”

**Comment by ramsey** [comment]
“moontoast/math” is the correct name of this package. I have Packagist set up so that, when requiring “moontoast/math,” it uses this repository and not the old one.
