### ISSUE TITLE
PHP 7.0 lint failure for moontoast/math/blob/master/tests/Moontoast/Math/BigNumberTest.php

### ISSUE THREAD

**Issue by yellowandy** [ramsey/moontoast-math#3]
PHP Parse error: Invalid numeric literal in vendor/moontoast/math/tests/Moontoast/Math/BigNumberTest.php on line 646

With php 7 invalid octal numbers get a warning thrown, saw this on line 622 as well.

**Comment by ramsey** [comment]
[Tests are passing on PHP 7.0, 7.1, and nightly](https://travis-ci.org/ramsey/moontoast-math/builds/202321236), without emitting any warnings or errors. Can you please provide some code or the commands you are running that are showing you this error? Thanks!

**Comment by yellowandy** [comment]
Looks like this was fixed with https://github.com/ramsey/moontoast-math/commit/8999ef71b418461ce6c17a635833ff47c9bbbb41#diff-75189eeda4ae0275ead44d6feb31bd7a .  Closing and sorry for not checking master, been a long day.
